### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by lydell** [aotarola/esbuild-elm-template#1]
- There is both index.html and public/index.html
- In app.ts I would recommend not mounting the app in `{ node: window.document.body }`. It’s very confusing when the body is replaced with a div. (I should update this in the example you copied this from as well. Edit: Fixed in my example.)
- Move the script tags back to `<body>` so you can get rid of `window.addEventListener("load", run);`. The `load` event can result in bad performance (it waits for a _lot_ of stuff): https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event
- There’s a TypeScript file (app.ts), but no tsconfig.json and TypeScript is missing in package.json. Either add those, or switch to app.js.
- postprocess.js has `minimal: !["Html", "Sandbox", "Element", "Document", "Worker"].includes(targetName)`, but there are no targets in elm-watch.json with those names.
- The comment linking to https://discourse.elm-lang.org/t/what-i-ve-learned-about-minifying-elm-code/7632 is missing in postprocess.js.
- LICENSE mentions your name, but I also have copyright since you copied from my example.
- Since this is based on my example, I think you should link to it: https://github.com/lydell/elm-watch/tree/main/example#readme
- The readme does not mention elm-test-rs (which is installed and used for the tests).
- package.json has `"test": "npm-run-all test:*"` which feels pretty overkill since it in practice only runs `npm run test:elm`. Btw, did you know that you can use run-pty for that? https://github.com/lydell/run-pty#--auto-exit
- You could add `"private": true` to package.json, since things using this template aren’t meant to be published to npm.
- You can remove description, repositiory, author, license, bugs, homepage from package.json since they aren’t needed for an app template.
- You might want to set up esbuild live reload: https://esbuild.github.io/api/#live-reload (I have it on my list adding this to my example)
- The installation instructions says `$ npx tiged aotarola/esbuild-elm-template my-elm-app` with a dollar sign in it (only for the first command, not for `npm ci`), so I cannot use the copy button (without having to go back and erase that dollar sign). Same thing for the usage instructions.
- The installation instructions are missing `cd my-elm-app`.
- The readme doesn’t have a link to http://localhost:9000/

**Comment by aotarola** [comment]
Hey @lydell thanks for taking the time and look at my template, I appreciate it a lot!

** _Andres is rolling his sleeves_ **
